### ISSUE TITLE
handler exception: [Errno -2] Name or service not known: failing to connect

### ISSUE THREAD

**Issue by mbana** [novnc/websockify#268]
hi, any clues as to why i am getting this error message?

version:

```sh
root@websockify_proxy:/# man websockify
bash: man: command not found
root@websockify_proxy:/# apt-cache show websockify
Package: websockify
Version: 0.8.0+dfsg1-7
Installed-Size: 68
Maintainer: PKG OpenStack <openstack-devel@lists.alioth.debian.org>
Architecture: amd64
Replaces: novnc (<< 1:0.4+dfsg+1-6)
Depends: python-numpy, python-websockify (>= 0.8.0+dfsg1-7) | python3-websockify (>= 0.8.0+dfsg1-7), libc6 (>= 2.4)
Breaks: novnc (<< 1:0.4+dfsg+1-6)
Description: WebSockets support for any application/server
Description-md5: 337cbf4b14d9c875bd13ec09c109dd7e
Homepage: https://pypi.python.org/pypi/websockify
Section: python
Priority: optional
Filename: pool/main/w/websockify/websockify_0.8.0+dfsg1-7_amd64.deb
Size: 24114
MD5sum: 2bedf579d7a18cbbae93682885927b3a
SHA256: ab0773d8945f068da4b4dfbbd89238f690081a0a34e81e05f6738604cf9f7537
root@websockify_proxy:/# uname -a
Linux websockify_proxy 4.9.8-moby #1 SMP Wed Feb 8 09:56:43 UTC 2017 x86_64 GNU/Linux
root@websockify_proxy:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
root@websockify_proxy:/# 
```

* when i the address without tcp it will block trying to connect, that is, `connecting to: tcp://172.17.0.4:4389` works whilst `connecting to: 172.17.0.4:4389` will just not progress.
* looking at the log i've attached below you can see that i can ping the source:

```sh
2017-02-19T21:42:01.211653606Z  + nc -w 1 -zv 172.17.0.4 4389
2017-02-19T21:42:01.211675182Z  websockify_server [172.17.0.4] 4389 (?) open
```

```sh
2017-02-19T21:41:58.180275440Z  172.17.0.5
2017-02-19T21:41:58.186540462Z  PING 172.17.0.5 (172.17.0.5): 56 data bytes
2017-02-19T21:41:58.186713369Z  64 bytes from 172.17.0.5: icmp_seq=0 ttl=64 time=0.137 ms
2017-02-19T21:41:58.186725356Z  --- 172.17.0.5 ping statistics ---
2017-02-19T21:41:58.186783891Z  1 packets transmitted, 1 packets received, 0% packet loss
2017-02-19T21:41:58.186791382Z  round-trip min/avg/max/stddev = 0.137/0.137/0.137/0.000 ms
2017-02-19T21:41:58.186946110Z  ---
2017-02-19T21:41:58.193822751Z  + websockify --verbose 172.17.0.5:4343 tcp://172.17.0.4:4389
2017-02-19T21:41:58.205233342Z  + sleep 3
2017-02-19T21:41:58.533722683Z  WebSocket server settings:
2017-02-19T21:41:58.533753649Z    - Listen on 172.17.0.5:4343
2017-02-19T21:41:58.533760342Z    - Flash security policy server
2017-02-19T21:41:58.533767733Z    - No SSL/TLS support (no cert file)
2017-02-19T21:41:58.534320817Z    - proxying from 172.17.0.5:4343 to tcp://172.17.0.4:4389
2017-02-19T21:42:01.211319978Z  + echo INFO
2017-02-19T21:42:01.211653606Z  + nc -w 1 -zv 172.17.0.4 4389
2017-02-19T21:42:01.211675182Z  websockify_server [172.17.0.4] 4389 (?) open
2017-02-19T21:42:10.016554044Z  172.17.0.1: new handler Process
2017-02-19T21:42:10.093373285Z  172.17.0.1 - - [19/Feb/2017 21:42:10] "GET / HTTP/1.1" 101 -
2017-02-19T21:42:10.113327761Z  172.17.0.1 - - [19/Feb/2017 21:42:10] 172.17.0.1: Plain non-SSL (ws://) WebSocket connection
2017-02-19T21:42:10.189268381Z  172.17.0.1 - - [19/Feb/2017 21:42:10] 172.17.0.1: Version hybi-13, base64: 'False'
2017-02-19T21:42:10.239350801Z  172.17.0.1 - - [19/Feb/2017 21:42:10] connecting to: tcp://172.17.0.4:4389
2017-02-19T21:42:10.354892116Z  handler exception: [Errno -2] Name or service not known
2017-02-19T21:42:10.361730400Z  exception
2017-02-19T21:42:10.361767258Z  Traceback (most recent call last):
2017-02-19T21:42:10.361799622Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 933, in top_new_client
2017-02-19T21:42:10.361805816Z      client = self.do_handshake(startsock, address)
2017-02-19T21:42:10.361811609Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 863, in do_handshake
2017-02-19T21:42:10.361817003Z      self.RequestHandlerClass(retsock, address, self)
2017-02-19T21:42:10.361822297Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 114, in __init__
2017-02-19T21:42:10.361827591Z      SimpleHTTPRequestHandler.__init__(self, req, addr, server)
2017-02-19T21:42:10.361832785Z    File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-02-19T21:42:10.361838080Z      self.handle()
2017-02-19T21:42:10.361843274Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 581, in handle
2017-02-19T21:42:10.361848868Z      SimpleHTTPRequestHandler.handle(self)
2017-02-19T21:42:10.361854062Z    File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-02-19T21:42:10.361859456Z      self.handle_one_request()
2017-02-19T21:42:10.361874939Z    File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-02-19T21:42:10.361881132Z      method()
2017-02-19T21:42:10.361886226Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 543, in do_GET
2017-02-19T21:42:10.361891420Z      if not self.handle_websocket():
2017-02-19T21:42:10.361896415Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 531, in handle_websocket
2017-02-19T21:42:10.361901609Z      self.new_websocket_client()
2017-02-19T21:42:10.361906703Z    File "/usr/lib/python2.7/dist-packages/websockify/websocketproxy.py", line 85, in new_websocket_client
2017-02-19T21:42:10.361911997Z      connect=True, use_ssl=self.server.ssl_target, unix_socket=self.server.unix_target)
2017-02-19T21:42:10.361918290Z    File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 715, in socket
2017-02-19T21:42:10.361923684Z      socket.IPPROTO_TCP, flags)
2017-02-19T21:42:10.361928779Z  gaierror: [Errno -2] Name or service not known
2017-02-19T21:42:10.364567440Z  Ignoring interrupted syscall
```

**Comment by CendioOssman** [comment]
`tcp://` isn't a valid URI scheme, so please remove that from the target.

**Comment by mbana** [comment]
yeh i've tried that initially and it blocks waiting to connect:

> when i the address without tcp it will block trying to connect, that is, connecting to: tcp://172.17.0.4:4389 works whilst connecting to: 172.17.0.4:4389 will just not progress.

do you have more logging i can turn on to help? otherwise, i can post steps on how to run the docker container that reproduces the issue. in any event, _i can_ connect to the target from the box websockify is running on.

**Comment by CendioOssman** [comment]
Not from websockify, no. So I'd check the logs in noVNC and the VNC server. Possibly also run `tcpdump` and see if that gives any clues.

**Comment by mbana** [comment]
seeing a lot of the below. full log is at https://gist.github.com/mbana/7297f20a223e7316765f445dd84c97e7#file-gistfile1-txt-L6572.

```sh
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 1 (in [4], left {tv_sec=0, tv_usec=585348})
accept(4, {sa_family=AF_INET, sin_port=htons(53150), sin_addr=inet_addr("172.17.0.1")}, [16]) = 5
gettimeofday({tv_sec=1487608846, tv_usec=443218}, NULL) = 0
write(2, "172.17.0.1: new handler Process\n", 32) = 32
write(3, "172.17.0.1: new handler Process\n", 32) = 32
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f045ae989d0) = 34
close(5)                                = 0
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608846, tv_usec=461037}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608847, tv_usec=467045}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608848, tv_usec=475114}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608849, tv_usec=487460}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608850, tv_usec=493291}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608851, tv_usec=500027}, NULL) = 0
```

many thanks

**Comment by mbana** [comment]
@CendioOssman 
unless you've fixed this, is it correct to call `select` on a closed fd?
`close(5)` then `select(5)`.

```sh
accept(4, {sa_family=AF_INET, sin_port=htons(53150), sin_addr=inet_addr("172.17.0.1")}, [16]) = 5
gettimeofday({tv_sec=1487608846, tv_usec=443218}, NULL) = 0
write(2, "172.17.0.1: new handler Process\n", 32) = 32
write(3, "172.17.0.1: new handler Process\n", 32) = 32
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f045ae989d0) = 34
close(5)                                = 0
wait4(34, 0x7fff51fcf58c, WNOHANG, NULL) = 0
wait4(33, 0x7fff51fcf58c, WNOHANG, NULL) = 0
gettimeofday({tv_sec=1487608846, tv_usec=461037}, NULL) = 0
select(5, [4], [], [], {tv_sec=1, tv_usec=0}) = 0 (Timeout)
```

**Comment by CendioOssman** [comment]
It is not. However you're not getting any errors so that suggests your strace is missing things. How did you start it?

**Comment by mbana** [comment]
i am running it within a container. the actual start command is:

```sh
2017-02-19T21:41:58.193822751Z  + websockify --verbose 172.17.0.5:4343 tcp://172.17.0.4:4389
```

i get a timeout (error). it forever waits for a connection to be made to the src (`tcp://172.17.0.4:4389`).

**Comment by CendioOssman** [comment]
Again, please don't use `tcp://` as you get a very explicit error for that.

How are you starting `strace`?

**Comment by mbana** [comment]
like so:

```sh
...
strace -o/var/log/websockify_proxy/strace.log 1>${WEBSOCKIFY_LOGFILE} 2>&1 websockify --verbose --log-file=/var/log/websockify_proxy/websockify.log --auto-pong ${HOSTNAME_PROXY}:4343 ${GO_LANGSERVER_SRC_ADDR}" \
...
```

`--log-file` isn't a valid option in my version of websockify, that shouldn't matter tho.

i think i mentioned that when i remove the tcp prefix it will just wait trying to connect:

> when i the address without tcp it will block trying to connect, that is, connecting to: tcp://172.17.0.4:4389 works whilst connecting to: 172.17.0.4:4389 will just not progress.

---

* is there a test program that you ship that allows one to check if everything works as intended? e.g., say a server running on tcp.
* running as a daemon just makese things more complicated in docker, so it's runnning in FG.
