### ISSUE TITLE
Error creating .exe 

### ISSUE THREAD

**Issue by Munkeynutz** [novnc/websockify#292]
Trying to create Windows .exe
I had to delete the code referencing Readme for long description
now it runs py2exe which BTW is a Py3 package...notsure why your saying get Py2.7 portable...

with the arguments to create a Win .exe it returns

running py2exe
running build_py
running egg_info
writing websockify.egg-info\PKG-INFO
writing dependency_links to websockify.egg-info\dependency_links.txt
writing entry points to websockify.egg-info\entry_points.txt
writing requirements to websockify.egg-info\requires.txt
writing top-level names to websockify.egg-info\top_level.txt
reading manifest file 'websockify.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'websockify.egg-info\SOURCES.txt'
Traceback (most recent call last):
  File "setupWIN.py", line 35, in <module>
    'websockify = websockify.websocketproxy:websockify_init',
  File "C:\ProgramData\Anaconda2\envs\py3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

I've installed through regular python method but .exe method is broken

**Comment by CendioOssman** [comment]
That seems to be a limitation in py2exe which doesn't work with newer versions of Python. Our Python code also doesn't work on Windows (#67), so it won't help using an older Python release.

I would suggest testing websockify.js, as we've had reports that people have gotten that up and running on Windows.
