### ISSUE TITLE
Uncaught Error: rQwait cannot backup 8 bytes

### ISSUE THREAD

**Issue by lgw8186** [novnc/websockify#364]
windows server 2008   + UltraVnc + novnc

When click on the link,    sometimes report 'Uncaught Error: rQwait cannot backup 8 bytes' ,  and I have a report 'Sorry, loopback connections are not enabled'.

noVNC 遇到一个错误：

1. 
Uncaught Error: rQwait cannot backup 8 bytes
http://xx:9000/core/websock.js:142:27
Error: rQwait cannot backup 8 bytes
    at Websock.rQwait (http://xx:9000/core/websock.js:142:27)
    at RFB._handle_security_failure (http://xx:9000/core/rfb.js:914:28)
    at RFB._negotiate_security (http://xx:9000/core/rfb.js:852:29)
    at RFB._init_msg (http://xx:9000/core/rfb.js:1274:29)
    at RFB._handle_message (http://xx:9000/core/rfb.js:709:22)
    at Websock._recv_message (http://xx:9000/core/websock.js:287:33)

2.
Sorry, loopback connections are not enabled

i have choose 'allow loopback connections ' on server-setting

please help me...

**Comment by CendioOssman** [comment]
This is an issue with noVNC. Could you please file this issue in that repo instead? Please include as many details as possible on how to set up a similar setup to yours.
