### ISSUE TITLE
Rebind.so

### ISSUE THREAD

**Issue by aerayth** [novnc/websockify#462]
I am using CentOS 8, using the latest code. I have installed WebSockify using Python 3.9.1.
`[centos@vps-80769e1f server]$ /usr/local/bin/websockify 13327 -- crossfire-server`
`Traceback (most recent call last):
  File "/usr/local/bin/websockify", line 33, in <module>
    sys.exit(load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')())
  File "/usr/local/lib/python3.9/site-packages/websockify/websocketproxy.py", line 725, in websockify_init
    server = WebSocketProxy(**opts.__dict__)
  File "/usr/local/lib/python3.9/site-packages/websockify/websocketproxy.py", line 306, in __init__
    raise Exception("rebind.so not found, perhaps you need to run make")
Exception: rebind.so not found, perhaps you need to run make`

I have used Python 3.9.1 and properly using the exact path to WebSockify which is installed via Pip.

**Comment by CendioOssman** [comment]
Have you run `make` as indicated in the error message?
