### ISSUE TITLE
webproxy to ovirt

### ISSUE THREAD

**Issue by pdemilly** [novnc/websockify#478]
Hi

OVirt uses TLSv1.2 to authenticate its session. It is my understanding that the websockify proxy should do the authentication at the time of creation (I might be wrong). But if so what would be the parameters to use to work. I tried the following following
```
websockify/run 5959
       --cafile=${CAFILE} \
	--ssl-target \
	--auth-plugin=ClientCertCNAuth \
	--auth-source="${user} ${password}"  \
	${host}:${port}
	

```

With CAFILE being the cert file returned by ovirt. user a string in the form:  O=xxxx.com,CN=d1c1v5.xxx.net and password as returned by the console.vv of ovirt.

But I am getting Authentication error:

```
xx.xx.xx.xx: new handler Process
Host: xxx.xxxxxxx.net:5959
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Upgrade: websocket
Origin: https://xx-xx-xx.xx.x
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8
Sec-WebSocket-Key: tl8ExsGUk3k0mHK5FKTomw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: binary

xx.xx.xx.xx - - [20/Mar/2021 01:19:42] "GET / HTTP/1.1" 403 -
handler exception: 403 None
exception
Traceback (most recent call last):
  File "/var/www/websockify/websockify/websockifyserver.py", line 662, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/var/www/websockify/websockify/websockifyserver.py", line 590, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/var/www/websockify/websockify/websockifyserver.py", line 87, in __init__
    super().__init__(req, addr, server)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/www/websockify/websockify/websockifyserver.py", line 297, in handle
    super().handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/var/www/websockify/websockify/websocketserver.py", line 40, in handle_one_request
    super().handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/var/www/websockify/websockify/websocketserver.py", line 50, in _websocket_do_GET
    self.handle_upgrade()
  File "/var/www/websockify/websockify/websockifyserver.py", line 201, in handle_upgrade
    self.auth_connection()
  File "/var/www/websockify/websockify/websocketproxy.py", line 77, in auth_connection
    self.server.auth_plugin.authenticate(
  File "/var/www/websockify/websockify/auth_plugins.py", line 103, in authenticate
    raise AuthenticationError(response_code=403)
websockify.auth_plugins.AuthenticationError: 403 None
^CIn exit
Closing socket listening at :5959
```

Thanks

**Comment by samhed** [comment]
It seems there has been a misunderstanding. Websockify can't authenticate with oVirt, it's just a Websockets-TCP proxy. The certificate and auth-plugin stuff in websockify is just for authenticating to Websockify, not to a third party thing, i.e who get's to use the proxy.

What problem are you trying to solve?

**Comment by pdemilly** [comment]
Thank you for your response. I am trying to understand how spice-html5 (a javascript spice protocol library) uses webproxy to interface with ovirt. The part that is mystifying me is authentication as I don't find anything in this lib code that shows how they authenticated. So I thought maybe websockify is providing this as well. I am now studying ovirt-websocket-proxy and it seems that they wrap their service over websockify and do the authentication there. Thanks for your time and sorry for the noise
