### ISSUE TITLE
handler exception: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by nmz787** [novnc/websockify#493]
I am trying to use websockify to proxy between local port 5901 and a different remote machine's port 1234, but getting this odd error:
```
$ python.exe -m websockify 5901 1.2.3.4:1234 --cert ..\secrets\ssl.crt --key ..\secrets\ssl.key
WARNING: no 'resource' module, daemonizing is disabled
WebSocket server settings:
  - Listen on :5901
  - SSL/TLS support
  - proxying from :5901 to 1.2.3.4:1234
handler exception: can't pickle _thread.RLock objects
handler exception: can't pickle _thread.RLock objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

I am running on this version of Python:
`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32`

and on websockify commit `dc345815c0c344de115278a37e837ba6a6f1b272`

**Comment by CendioOssman** [comment]
Hmmm.. This worked as of #388. Not sure why things are broken again.
